### ISSUE TITLE
Is this being maintained

### ISSUE THREAD

**Issue by ozak** [MattDMo/PythonImproved-atom#1]
Hi @MattDMo I used your package on Sublime and wanted to use it also on Atom. Are you maintaining this one? Any reason it is not being ported? Thanks!

**Comment by MattDMo** [comment]
@ozak thanks for the feedback. Unfortunately, I really haven't had any time to update either the original PI for Sublime, or the Atom version, as work and family life have been very demanding for quite some time now. If you have particular changes you'd like to make, feel free to submit PRs and I'll take a look at them.

**Comment by ozak** [comment]
No changes, just seems Python works better/faster in ST3 than in Atom...so I was trying to install this also on Atom, but could not find it in their package manager. So thought the project had been abandoned. And since ST3 has been rumored to have been abandoned (or at least seems to provide upgrades very slowly), so I was trying to decide what the best option was.

**Comment by MattDMo** [comment]
Rumors of ST3 being abandoned circulate every time they don't put out a new release every other week. I can tell you for certain, it is NOT being abandoned - I'm in a Github group with Will Bond, one of ST's main developers, and I get emails from it practically every day. The .sublime-syntax highlighting files are being worked on extensively, and new bug reports are submitted and triaged frequently, so I wouldn't worry about that.

I prefer Sublime over Atom, which is part of the reason why I haven't maintained this particular package in my rather small free time, but pick whatever works best for you.

**Comment by ozak** [comment]
I'm still undecided... They both have cool features. 
That's for the info!

**Comment by MattDMo** [comment]
No problem, thanks for writing. The final piece of advice I'll give you is this: you don't have to pick just one. It may be that you *really* want a certain feature from one that isn't in the other, so use it for that, and use the other for everything else. There's nothing saying that you can't use both. Of course, if you're using Sublime full-time for commercial work, you'll need a license (which I think is around US$75 or so), but that also means you can use the developer releases, which are generally more advanced than the public beta.

Anyways, good luck!

Matt
